name: Python CI

on: [push, workflow_dispatch]

jobs:
  PythonVersionSetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: |
          pwd
          ls -l

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - run: python --version
      - run: pip --version

      - name: Install dependencies
        working-directory: test03
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install pytest pytest-cov
          poetry install

      - name: Run Tests
        working-directory: test03
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Build
        working-directory: test03
        run: poetry build

      - name: Debug Build Output
        working-directory: test03
        run: ls -l dist
